version: '3.1'

services:
  # https://hub.docker.com/_/elasticsearch
  elasticsearch:
    image: elasticsearch:7.6.2
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: secretpassword1
      discovery.type: single-node
    expose:
      - '9200'
      - '9300'
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - elk_network
    volumes:
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "elasticsearch:/usr/share/elasticsearch/data"
  # https://hub.docker.com/_/logstash
  logstash:
    # build:
    #   context: .
    # command: --innodb-use-native-aio=0 #This is needed for some reason for mountind the DB data volume to the container...
    image: logstash:7.6.2
    restart: always
    environment: 
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    expose:
      - '5044'
      - '5959'
    ports:
      - 5044:5044
      - 5959:5959
    volumes:
      - "./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro"
      - "./logstash//pipeline/:/usr/share/logstash/pipeline:ro"
    networks: 
      - elk_network
    depends_on: 
      - elasticsearch
  # https://hub.docker.com/_/kibana
  kibana:
    image: kibana:7.6.2
    restart: always
    environment: 
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports: 
      - 5601:5601
    expose:
      - '5601'
    depends_on: 
      - elasticsearch
    networks: 
      - elk_network
    volumes:
      - "./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    
networks: 
  elk_network:

volumes:
  elasticsearch: