version: '3.1'

services:
# https://hub.docker.com/_/mysql
  mysql:
    # build:
    #   context: .
    # command: --innodb-use-native-aio=0 #This is needed for some reason for mountind the DB data volume to the container...
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: testdb
      # MYSQL_USER: testuser
      # MYSQL_PASSWORD: password
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # MYSQL_RANDOM_ROOT_PASSWORD: yes
      # MYSQL_ONETIME_PASSWORD: one_time_password_for_root
    ports:
      - 3306:3306
      - 33060:33060
    expose:
      - '3306'
      - '33060'
    volumes:
      - "./data:/var/lib/mysql"
      - "./init-db:/docker-entrypoint-initdb.d"
    