version: '3.1'

services:
  postgres:
    # build:
    #   context: .
    # command: --innodb-use-native-aio=0 #This is needed for some reason for mountind the DB data volume to the container...
    image: postgres:latest
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: password      
    ports:
      - 5432:5432
    expose:
      - '5432'
    volumes:
      # - "./data:$PGDATA"
      - "postgres_data:/var/lib/postgresql/data" # docker volume create --name postgres_data --driver local
      - "./init-db:/docker-entrypoint-initdb.d"
volumes:
  postgres_data:
    external: true

    